# Generated by Django 5.2.7 on 2025-11-18 12:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[("#800080", "Purple"), ("#FF69B4", "Pink")],
                        max_length=7,
                    ),
                ),
                ("category", models.CharField(max_length=30)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("date_creation", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_assigned_set",
                        to="myauth.user",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_owner_set",
                        to="myauth.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("members", models.ManyToManyField(to="myauth.user")),
                (
                    "archived",
                    models.ManyToManyField(
                        related_name="board_archived_set", to="myboard.task"
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="board_tasks_set", to="myboard.task"
                    ),
                ),
            ],
        ),
    ]
