# Generated by Django 5.2.7 on 2026-01-01 11:50

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("myauth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=30),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "admin",
                    models.ManyToManyField(
                        related_name="board_admin_set", to="myauth.user"
                    ),
                ),
                ("members", models.ManyToManyField(to="myauth.user")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_owner_set",
                        to="myauth.user",
                    ),
                ),
                (
                    "user_favorite",
                    models.ManyToManyField(
                        related_name="board_favorite_set", to="myauth.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "color",
                    models.CharField(
                        choices=[("#800080", "Purple"), ("#FF69B4", "Pink")],
                        default="#800080",
                        max_length=7,
                    ),
                ),
                ("category", models.CharField(max_length=30)),
                ("date_start", models.DateTimeField(blank=True, null=True)),
                ("date_end", models.DateTimeField(blank=True, null=True)),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("completed", models.BooleanField(default=False)),
                (
                    "assigned",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_assigned_set",
                        to="myauth.user",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_owner_set",
                        to="myauth.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardTasksThroughModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myboard.board"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myboard.task"
                    ),
                ),
            ],
            options={
                "ordering": ("board", "order"),
            },
        ),
        migrations.AddField(
            model_name="board",
            name="archived",
            field=models.ManyToManyField(
                related_name="board_archived_set", to="myboard.task"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="tasks",
            field=models.ManyToManyField(
                related_name="board_tasks_set",
                through="myboard.BoardTasksThroughModel",
                to="myboard.task",
            ),
        ),
    ]
