# Generated by Django 5.2.7 on 2026-01-01 12:26

import ordered_model.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="tasks",
            field=ordered_model.fields.OrderedManyToManyField(
                related_name="board_tasks_set",
                through="myboard.BoardTasksThroughModel",
                to="myboard.task",
            ),
        ),
    ]
