# Generated by Django 5.2.7 on 2026-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0002_alter_board_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="color",
            field=models.CharField(
                choices=[
                    ("#800080", "Purple"),
                    ("#FF69B4", "Pink"),
                    ("#000000", "Noir"),
                    ("#7FFF00", "Vert"),
                ],
                default="#000000",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.CharField(
                choices=[
                    ("#800080", "Purple"),
                    ("#FF69B4", "Pink"),
                    ("#000000", "Noir"),
                    ("#7FFF00", "Vert"),
                ],
                default="#800080",
                max_length=7,
            ),
        ),
    ]
