# Generated by Django 5.2.7 on 2025-12-25 15:08

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_user_profile_picture"),
        ("myboard", "0003_alter_task_color_alter_task_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="admin",
            field=models.ManyToManyField(
                related_name="board_admin_set", to="myauth.user"
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_creation",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
