# Generated by Django 5.2.7 on 2026-01-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myboard', '0003_board_color_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(default='#800080', max_length=8),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#800080', max_length=8),
        ),
    ]
