# Generated by Django 6.0 on 2026-01-25 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0001_initial"),
        ("myboard", "0004_alter_board_color_alter_task_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConnected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nb_connected", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myauth.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="board",
            name="user_connected",
            field=models.ManyToManyField(to="myboard.userconnected"),
        ),
    ]
