# Generated by Django 5.2.7 on 2025-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0004_board_admin_board_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.CharField(
                choices=[("#800080", "Purple"), ("#FF69B4", "Pink")],
                default=[("#800080", "Purple"), ("#FF69B4", "Pink")],
                max_length=7,
            ),
        ),
    ]
