# Generated by Django 5.2.7 on 2025-12-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0005_alter_task_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="color",
            field=models.CharField(
                choices=[("#800080", "Purple"), ("#FF69B4", "Pink")],
                default="#800080",
                max_length=7,
            ),
        ),
    ]
