# Generated by Django 5.2.7 on 2025-12-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0003_alter_user_authprovider"),
        ("myboard", "0006_alter_task_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="favorite",
            field=models.ManyToManyField(
                related_name="board_favorite_set", to="myauth.user"
            ),
        ),
    ]
