# Generated by Django 5.2.7 on 2025-12-31 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myboard", "0007_board_favorite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="favorite",
            new_name="user_favorite",
        ),
    ]
