# Generated by Django 5.2.7 on 2025-11-04 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("profile_picture", models.URLField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "authprovider",
                    models.CharField(choices=[("ggl", "Google")], max_length=3),
                ),
                ("authuserid", models.CharField(max_length=30)),
            ],
        ),
    ]
