# Generated by Django 6.0 on 2026-01-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nb_board',
            field=models.IntegerField(default=0),
        ),
    ]
