# Generated by Django 5.2.7 on 2025-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="authprovider",
            field=models.CharField(
                choices=[("ggl", "Google"), ("tst", "Test")], max_length=3
            ),
        ),
    ]
