# Generated by Django 6.0 on 2026-01-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0002_user_nb_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nb_task",
            field=models.IntegerField(default=0),
        ),
    ]
